export const FETCH_SCHOLARSHIPS_START = "FETCH_SCHOLARSHIPS_START";
export const FETCH_SCHOLARSHIPS_SUCCESS = "FETCH_SCHOLARSHIPS_SUCCESS";
export const FETCH_SCHOLARSHIPS_FAILURE = "FETCH_SCHOLARSHIPS_FAILURE";

export const SAVE_FORM_DATA = "SAVE_FORM_DATA";
export const NEXT_STEP = "NEXT_STEP";
export const PREV_STEP = "PREV_STEP";
export const RESET_FORM_DATA = "RESET_FORM_DATA";

export const SUBMIT_APPLICATION_START = "SUBMIT_SCHOLARSHIP_START";
export const SUBMIT_APPLICATION_SUCCESS = "SUBMIT_SCHOLARSHIP_SUCCESS";
export const SUBMIT_APPLICATION_FAILURE = "SUBMIT_SCHOLARSHIP_FAILURE";

export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_THEME = 'SET_THEME';